#########################################################################
#									#
# File ID: ./.travis.yml						#
# Author: Copyright (C) 2019  Mark Grant				#
#									#
# Released under the GPLv3 only.					#
# SPDX-License-Identifier: GPL-3.0					#
#									#
# Configuration file for Travis CI build tests.				#
#									#
#########################################################################

#########################################################################
#									#
# Changelog								#
#									#
# Date		Author	Version	Description				#
#									#
# 06/11/2019	MG	1.0.1	Initial release.                        #
#                               Bionic is now the minimum distribution  #
#                               due to dependencies built on LaunchPad. #
#                               No need to specify my -dev packages as  #
#                               they are in the main packages.          #
#									#
#########################################################################


language: c

dist:
    - bionic

before_install:
    - sudo add-apt-repository ppa:m-grant-prg/utils -y
    - sudo apt-get update
    - sudo apt-get install -y autoconf-archive libtool-bin
    - sudo apt-get install -y dia doxygen graphviz
    - sudo apt-get install -y libssh-gcrypt-dev libssh-gcrypt-4
    - sudo apt-get install -y libmgec2 libmgesysutils1
    - sudo apt-get install -y txt2man txt2manwrap

script:
    - autoreconf -if .
    - ./configure --enable-silent-rules=yes
    - make --quiet
    - make --quiet check
    - make --quiet distcheck

after_failure:
    - cat */_build/sub/src/prg/c/src/*/*.log

