#########################################################################
#									#
# File ID: ./.github/workflows/build-test.yml				#
# Author: Copyright (C) 2021-2023  Mark Grant				#
#									#
# Released under the GPLv3 only.					#
# SPDX-License-Identifier: GPL-3.0-only					#
#									#
# Purpose:								#
# Configuration file for GitHub Actions build tests. Perform a standard #
# build, check and distcheck.                   			#
#									#
#########################################################################

#########################################################################
#									#
# Changelog								#
#									#
# Date		Author	Version	Description				#
#									#
# 01/03/2021	MG	1.0.1	Initial release.                        #
# 14/10/2021    MG      1.0.2   New minimum platform of focal.          #
# 07/12/2021    MG      1.0.3   Get tags as needed for git-enhanced     #
#                               AC_INIT.                                #
#                               Tighten SPDX tag.                       #
# 21/11/2022    MG      1.0.4   Use new libmgec7 and libmgesysutils2.   #
# 13/07/2023    MG      1.0.5   Run on 22.04.                           #
# 31/07/2023    MG      1.0.6   Remove txt2man install, rely on         #
#                               dependencies.                           #
#									#
#########################################################################


name: Build Test

on:
  push:

  # Allows manual invocation from the Actions tab.
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-22.04

    steps:
      # Check-out the repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Get all incl tags, needed for git-enhanced AC_INIT

      - name: Add the extra PPA
        run: sudo add-apt-repository ppa:m-grant-prg/utils -y
      - name: Update the package lists
        run: sudo apt-get update
      - name: Add the extra packages
        run: |
          sudo apt-get install -y autoconf-archive libtool-bin
          sudo apt-get install -y doxygen graphviz
          sudo apt-get install -y libssh-gcrypt-dev libssh-gcrypt-4
          sudo apt-get install -y libmgec7-dev libmgec7
          sudo apt-get install -y libmgesysutils2-dev libmgesysutils2
          sudo apt-get install -y txt2manwrap

      - name: Autoreconf
        run: autoreconf -if .
      - name: Configure
        run: ./configure --enable-silent-rules=yes
      - name: Make
        run: make --quiet

      - name: Check
        run: make --quiet check

      - name: Distcheck
        run: make --quiet distcheck

